### ISSUE TITLE
Intermittent test failure: DECODER routines::unsupported

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#1212]
https://github.com/getodk/central-backend/actions/runs/10702632292/job/29671272325

```
2024-09-04T13:27:47.9903658Z   managed encryption
2024-09-04T13:27:47.9904491Z     lock management
2024-09-04T13:27:48.2104194Z       ✔ should reject keyless forms in keyed projects @slow (221ms)
2024-09-04T13:27:49.0429483Z       ✔ should reject forms created while project managed encryption is being enabled @slow (184ms)
2024-09-04T13:27:49.6529419Z     decryptor
2024-09-04T13:27:50.0331955Z       ✔ should give a decryptor for the given passphrases (380ms)
2024-09-04T13:27:50.0333106Z     encrypted submission attachment parsing
2024-09-04T13:27:50.0344764Z       ✔ should correctly record attachment file ordering
2024-09-04T13:27:50.0347678Z     end-to-end
2024-09-04T13:27:50.0410796Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/sessions HTTP/1.1" 200 228
2024-09-04T13:27:50.2878107Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/key HTTP/1.1" 200 16
2024-09-04T13:27:50.2907190Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple.xml HTTP/1.1" 200 1285
2024-09-04T13:27:50.2980087Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/forms/simple/submissions HTTP/1.1" 200 305
2024-09-04T13:27:50.3029627Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/forms/simple/submissions/one/attachments/submission.xml.enc HTTP/1.1" 200 16
2024-09-04T13:27:50.3062329Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple/submissions/keys HTTP/1.1" 200 492
2024-09-04T13:27:50.3429563Z Error: error:1E08010C:DECODER routines::unsupported
2024-09-04T13:27:50.3430688Z     at createPrivateKey (node:internal/crypto/keys:632:12)
2024-09-04T13:27:50.3432370Z     at /home/runner/work/central-backend/central-backend/lib/util/crypto.js:156:14
2024-09-04T13:27:50.3433409Z     at async Promise.all (index 0) {
2024-09-04T13:27:50.3433866Z   library: 'DECODER routines',
2024-09-04T13:27:50.3434488Z   reason: 'unsupported',
2024-09-04T13:27:50.3435064Z   code: 'ERR_OSSL_UNSUPPORTED'
2024-09-04T13:27:50.3435810Z }Error: error:1E08010C:DECODER routines::unsupported
2024-09-04T13:27:50.3436874Z     at createPrivateKey (node:internal/crypto/keys:632:12)
2024-09-04T13:27:50.3438123Z     at /home/runner/work/central-backend/central-backend/lib/util/crypto.js:156:14
2024-09-04T13:27:50.3439090Z     at async Promise.all (index 0) {
2024-09-04T13:27:50.3439738Z   library: 'DECODER routines',
2024-09-04T13:27:50.3440302Z   reason: 'unsupported',
2024-09-04T13:27:50.3440860Z   code: 'ERR_OSSL_UNSUPPORTED'
2024-09-04T13:27:50.3443347Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple/submissions.csv.zip?4=wrong HTTP/1.1" 500 35
2024-09-04T13:27:50.3452770Z       1) should reject with a reasonable message given incorrect passphrase
```

```
  2437 passing (2m)
  20 pending
  1 failing

  1) managed encryption
       end-to-end
         should reject with a reasonable message given incorrect passphrase:
     Error: expected 400 "Bad Request", got 500 "Internal Server Error"
      at /home/runner/work/central-backend/central-backend/test/integration/other/encryption.js:204:14
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transaction (node_modules/slonik/dist/src/connectionMethods/transaction.js:22:24)
      at async Object.createConnection (node_modules/slonik/dist/src/factories/createConnection.js:97:18)
  ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at /home/runner/work/central-backend/central-backend/node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)
      at Object.onceWrapper (node:events:628:28)
      at Server.emit (node:events:514:28)
      at Server.emit (node:domain:488:12)
      at emitCloseNT (node:net:2273:8)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21)



    at process.processImmediate (node:internal/timers:478:21)make: *** [Makefile:58: test] Error 1
```

**Comment by matthew-white** [comment]
This looks like the same test that's failing in #499, but a different error code. Here, the error code is `ERR_OSSL_UNSUPPORTED`, whereas in #499, it's `ERR_OSSL_PEM_NO_START_LINE`.

**Comment by alxndrsn** [comment]
Seen today: https://app.circleci.com/pipelines/github/alxndrsn/odk-central-backend/2149/workflows/6a727019-d295-49c2-a382-3ebdb0e0c401/jobs/2077/parallel-runs/0/steps/0-106

**Comment by alxndrsn** [comment]
Seen today at https://github.com/alxndrsn/odk-central-backend/actions/runs/13131375875/job/36637115601

**Comment by alxndrsn** [comment]
To recreate:

```js
o = {"keys":{"iv":"7+ELinzekqZOaOiGSRgYxw==","salt":"7jE50XhstDF97pN4YlPS/g==","pubkey":"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxcHR1dnhpQWtINE5vdVRJTU1sVQp1Q2VxODJjNXdaZWEyQ3R4Uzg1U1A2NCsxQWJLSHdHWDhXYU5YRTNyUlZOQ3l5SzYvQTlWSWJ3ZWg5OXZjOEhnCnI2bFplcjhwOGhtTlFheXdUbThHczA2NllNTkQ3SExVY2h4dmdML2xYQjVwYlVtNDk1VkQrbE9HODJkbEExTSsKODFTTHBhaUovSzdNcVhHK2ZwbkM0UXpVWlRNMXY5RUlyRTVvbDFVL1JYQi9IZERzaXRwNnlROEJwNm5TdVlzRQoveURwUlNGTEFCZWFCTkN6cGxLZHY5ZVFaSmdtNjV2MVcxNlBteGNNRmVXM21RcHJOWTczZ1YvUFpCL25vTjdlClZ2cXl6R0hHajlJZmFBMnVjandVYmxjbFFVNElIR1FBaEtCZGlReEpHL1g2TDVqdVpQU3NYQW5NbENqR21vWm4KU1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==","privkey":"+sMs6tIbJE9S4NicQtDFsAUazH4ajwxGhEjq+Pj7lxZ1ICA5pQEOj/cGBSADVa/BV0tp3j04fw2r+ocJHclccUMhVfEE9RRzMB1G3/3T+Ch7YqPs4+tPG2EbDwl4DAnw9uYKS9qqIRhfEB49uOg3aqYNk2E50rXhHSjW+3BmZnRqa0AzZElMxAqWKfSq6Qe88wm9ePN+xChO09s5luTQOfDXKp277Hy7wCulhz6Q1I2nyjvVtQI1gZz1xzD2YdFSbhgD/a/qaTpVnT5/wToFXyAi7vQEYWignw2zyKpk3/QVc6dKUYALA7ogxO6V9X/M9z2YZ9JbwqkIxWp8m7VogQLEvjm/7Pidz5iykTLkslUt3HXsIFrAarvJOkS1eeC0pWj2y9g+xZqDGvKg0v3kWRILMc1u4L+3KYnrreU6s5+dKyKQm6jinPjF5pZ+gOVVx9fp9zsLgMeiLnX8FCQNaHF8Dulji+O9U8mY6XQo6HFLpjKKuMDhy/SkQEytA/vF4D7Y+OuOuPlzpZuKRRW8UhxKgDgc9jVlpXZXyUkn9F9Eu5C1JKET5+WZlNYJdnpbJFugaVdNyutQxc/YTm7iqllHVJkELGKz5dQg3T7JzUjOWSsbsxWNT2Ozt9UZqYwmUJtghkopeZDaDeBys2P6a862yu8jXSOtHuxxiwvTMHiNKrD53kg/Qgw2pv4qQi5bBWB0B6lEonrVNKi9bugOFAjjwQCP8S98SXsgVzl9JXjKBQBt5wU/AQ/QI3ov9jsfeTiyjgo9DMYqGDL0YCOEO7W0ZQG4Hjgw2XdWgB+xmU3x/msNZb8uFBkx503pBI7X42AKJknfFEcjCfYDcfaCRAlp7zifcJ3TRJuuoIdhnVgoKOMBJl/GHpk85Rq5FgN3YZYOObirbnop8rUJKM7RN1/nSm97tXKY+kS1o7b+Di+cxO9w8gV/eb06MAgtq75jEO+wIvMpMuxfS02xdOWTWjkwGoyqsS4aUK7T2kY8595Bh3rMRFsAjgp6+2+PemOEjcBurXGs2+U8oEgPOPJc9erhZSRy0UZk6ciPW8jqfs5Y+//8Dxd4Q9prAIPoKulPwrhEkDGC3o1rxXflHbkFjlCUAz7WapvpdOBB6rkXWs6ttphLAdAO9c8qdkrGfskI+FMdcKCpPrfAGVQlIStrEPmzcEgQHKRUJs3Rn2EzgrnPyBUNxIDOYi7b83tT2Lzx6wttkeOx7dp7v8zBtW/umJdhEFrIL7swxogez2mb5fhjWt+I4r4fNMV5rJusLU0yEv7kHK/m7Sb55G7CKeVbhPE9PX6sII5z/XhfXrcJqG3+Z52r5aknG3H2k/7EHkZ/jXRNkVA+vPWi4ViATMTW2YT1JYHbkoD211OKSOmtafdII76N3Jjz3N74VsFrbZZI8etNIeg7FEBhguH7HGVO/O1uDcsSEGI1Qu6ts5OFRdSy7mVj/0lsKowVyipkFwwAEk3fQhdvmQodhv8fhitos7iWvlB6UhxQpt0ELMNTNeIbyedo0B9RHLZheOEKVxYvoNXTYW9aRn38CVg72pCbMPnstI10rxbhZohFY9v2ClbJqXPe3EXEyxM8pq498yvYn1BjulPUJAaTGpHSAIKgclBkElcLMXqohJ/C4F4hgIzUApQrGQByeILmNz+RwKyY13NgF4JJpwb1WgDRX30x3xqJE5rVgVsC0RgEzy5BNfwC7tkajfgQzWNBPzwKB2E9Pc0G/357mxAOkujSyMLWdZYBpy6NsFAmlvK+WgeAuKb/MIdL6Ak8ImToSVHr8U3FZ6LjzznSIs/iA4G2euAyY4PsA7HPLRYWod/2d+3DgqrONgE5szXc2sxlfVjbWzGKbnZGHgNuhriekl2G/FtRDmURUI/tI5hklrTApYi0TeM6xN0j2BVi6rVaTggI5sH6Ra7/xGNaQBiJBqN8DKZpbnZfA1kzwZF8XkQJkmAzS8jfbS2JoT7C/U+icKA8trRRmdftO/jztUk7uor+kPY+C0QpVxA1IAH9CqCOWGUmCktSBQ29K8/2iU/eu9BhB7Cn/EzRwCvInIOnXIQipjWzK0H5Zg/Dg7/lb7ez5ne10iwnNbxWOdRR2gRTFP6A7mb8/O7fMov5HzGJS60/K6rLORLV9g9Pzc95GuVfyzNZGs4xyhsDxmjoQjTES/sZaegf2JSzr9emBwlwFfwmBbD7T25Y7Q6oVxOUs/5YXkD0mkaJaepOHjKpsMLy0f+wfcB7phAMDUx6Aelowf2NtIgDp2wnFZaGeeH8cnyStNlGgPQ="},"passphrase":"wrong"};

require('./lib/util/crypto').getPrivate(o.keys, o.passphrase);
```
