### ISSUE TITLE
Intermittent test failure: DataIntegrityError: Query returns an unexpected result.

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#1330]
https://github.com/getodk/central-backend/actions/runs/12176766700/job/33963182079#step:8:16411

```

  1) managed encryption
       end-to-end @slow
         should decrypt client audit log attachments from s3:
     DataIntegrityError: Query returns an unexpected result.
      at Object.maybeOne (node_modules/slonik/dist/src/connectionMethods/maybeOne.js:22:15)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /home/runner/work/central-backend/central-backend/lib/model/query/blobs.js:155:23
      at async uploadBlobIfAvailable (lib/model/query/blobs.js:154:15)
      at async /home/runner/work/central-backend/central-backend/lib/model/query/blobs.js:185:12
      at async Object.transaction (node_modules/slonik/dist/src/connectionMethods/transaction.js:22:24)
      at async Object.createConnection (node_modules/slonik/dist/src/factories/createConnection.js:97:18)
```

**Comment by alxndrsn** [comment]
Seen again: https://github.com/getodk/central-backend/actions/runs/13128251970/job/36628516337

**Comment by alxndrsn** [comment]
Closing in favour of https://github.com/getodk/central-backend/issues/1373, as that ticket is more specific.
