### ISSUE TITLE
Command line tool displays warning

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#419]
When I run `odk-cmd user-create` on a server running v1.3, I see the following warning:

```
(node:509) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

I then ran the following command:

```sh
docker-compose exec service node --trace-warnings lib/bin/cli.js --email example@getodk.org user-create
```

and saw the following results:

```
(node:369) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:674:11)
    at Object.get (internal/modules/cjs/loader.js:688:5)
    at Object.exports.setLevels (/usr/odk/node_modules/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/usr/odk/node_modules/winston/lib/winston.js:84:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/odk/node_modules/prompt/lib/prompt.js:14:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

**Comment by matthew-white** [comment]
This warning was mentioned on the forum here: https://forum.getodk.org/t/warning-accessing-non-existent-property-padlevels-of-module-exports-inside-circular-dependency/35577
