### ISSUE TITLE
Intermittent test failure: managed encryption > end-to-end > should reject with a reasonable message given incorrect passphrase

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#499]
I've seen this test fail once, as the only failure in the whole suite:

```
  1) managed encryption
       end-to-end
         should reject with a reasonable message given incorrect passphrase:
     Error: expected 400 "Bad Request", got 500 "Internal Server Error"
      at Test._assertStatus (node_modules/supertest/lib/test.js:266:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.assert (node_modules/supertest/lib/test.js:171:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at Server.emit (domain.js:475:12)
      at emitCloseNT (net.js:1677:8)
      at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

Scrolling back up the logs:

```
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "POST /v1/sessions HTTP/1.1" 200 228
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "POST /v1/projects/1/key HTTP/1.1" 200 16
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "GET /v1/projects/1/forms/simple.xml HTTP/1.1" 200 1285
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "POST /v1/projects/1/forms/simple/submissions HTTP/1.1" 200 127
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "POST /v1/projects/1/forms/simple/submissions/one/attachments/submission.xml.enc HTTP/1.1" 200 16
::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "GET /v1/projects/1/forms/simple/submissions/keys HTTP/1.1" 200 492
Error: error:0909006C:PEM routines:get_name:no start line
    at createPrivateKey (internal/crypto/keys.js:351:10)
    at /x/central-backend/lib/util/crypto.js:151:14
    at async Promise.all (index 0) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}Error: error:0909006C:PEM routines:get_name:no start line
    at createPrivateKey (internal/crypto/keys.js:351:10)
    at /x/central-backend/lib/util/crypto.js:151:14
    at async Promise.all (index 0) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}::ffff:127.0.0.1 - - [23/Jun/2022:08:39:04 +0000] "GET /v1/projects/1/forms/simple/submissions.csv.zip?4=wrong HTTP/1.1" 500 339
      1) should reject with a reasonable message given incorrect passphrase
```

**Comment by matthew-white** [comment]
Thanks for filing this! That message rings a bell for me: I think I've seen this intermittent test failure as well.

**Comment by alxndrsn** [comment]
This is still happening for me :slightly_frowning_face:

**Comment by matthew-white** [comment]
This is also happening for me on occasion locally.

**Comment by alxndrsn** [comment]
I expect this will be closed by https://github.com/getodk/central-backend/pull/1386 - it seems likely that the underlying SSL error has changed over time.

Repeated test re-reruns will give more confidence. Current count: 512 runs passed OK:

* https://github.com/alxndrsn/odk-central-backend/actions/runs/13140437138
* https://github.com/alxndrsn/odk-central-backend/actions/runs/13140437144

**Comment by matthew-white** [comment]
@alxndrsn, do you think that this was resolved by #1386? One option is that we could close this issue, then reopen it if we see this test failure again.
