### ISSUE TITLE
Return Problem response if user specifies too large number

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-backend#514]
Right now, if a number is specified to Backend that is too large, Backend can return a 500 error. For example, when I send a request to /v1/projects/10000000000 locally, I receive a 500 error response with the following body:

```json
{
  "message": "Completely unhandled exception: value \"10000000000\" is out of range for type integer",
  "details": {
    "stack": [
      "error: value \"10000000000\" is out of range for type integer",
      "at Parser.parseErrorMessage (/central-backend/node_modules/pg-protocol/dist/parser.js:278:15)",
      "at Parser.handlePacket (/central-backend/node_modules/pg-protocol/dist/parser.js:126:29)",
      "at Parser.parse (/central-backend/node_modules/pg-protocol/dist/parser.js:39:38)",
      "at Socket.<anonymous> (/central-backend/node_modules/pg-protocol/dist/index.js:10:42)",
      "at Socket.emit (events.js:400:28)",
      "at Socket.emit (domain.js:470:12)",
      "at addChunk (internal/streams/readable.js:290:12)",
      "at readableAddChunk (internal/streams/readable.js:265:9)",
      "at Socket.Readable.push (internal/streams/readable.js:204:10)",
      "at TCP.onStreamRead (internal/stream_base_commons.js:188:23)"
    ]
  }
}
```

This can be seen in [this](https://sentry.io/organizations/getodk/issues/3375582060/?environment=production) Sentry error.

Instead of returning a 500 error, I think it'd be better for Backend to return a 400 Problem response. We do that already for non-numeric input: see #135 (fixed in #182).

**Comment by seifbhxc65** [comment]
you still having the problem?

**Comment by matthew-white** [comment]
Hi @seifbhxc65! Yes, this is still an issue. (I actually just filed this issue yesterday!)
