### ISSUE TITLE
Increase test timeout or make it configurable

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#532]
I frequently see local test failures for `make test` due to timeouts, and also the initial test setup can timeout.  Some of the failures do not make it clear that the problem was a timeout.

It would be helpful to either increase the default test timeout, or allow configuration of a scale factor via an env var, e.g. `ODK_CENTRAL_BACKEND_TEST_TIMEOUT_SCALE_FACTOR=2`.

## Startup failure

```
env BCRYPT=no node node_modules/mocha/bin/mocha --recursive --exit


  1) "before all" hook: initialize in "{root}"

  0 passing (2s)
  1 failing

  1) "before all" hook: initialize in "{root}":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

## Test failures

Note this is a specific example - different tests can time out.

```
  ...
  1667 passing (2m)
  8 pending
  4 failing

  1) enketo worker transaction
       should not allow a write conflict @slow:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/other/transactions.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  2) task: accounts
       createUser
         should create a user account:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  3) task: accounts
       createUser
         should log an audit entry:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  4) task: accounts
       createUser
         should set the password if given:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by matthew-white** [comment]
An example of test timeouts in CircleCI: https://app.circleci.com/pipelines/github/getodk/central-backend/747/workflows/42e5508e-6606-4602-996a-9ecb4c61e115/jobs/1488. In this case, the two tests that failed were both marked `@slow`.

**Comment by alxndrsn** [comment]
Here's another failure example:

```
  1) managed encryption
       lock management
         should reject keyless forms in keyed projects @slow:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/other/encryption.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  2) managed encryption
       lock management
         should reject forms created while project managed encryption is being enabled @slow:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/other/encryption.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  3) managed encryption
       decryptor
         should give a decryptor for the given passphrases:
     error: relation "keys" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  4) managed encryption
       end-to-end
         should reject with a reasonable message given incorrect passphrase:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/other/encryption.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  5) enketo worker transaction
       should not allow a write conflict @slow:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/other/transactions.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  6) task: accounts
       createUser
         should create a user account:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  7) task: accounts
       createUser
         should log an audit entry:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  8) task: accounts
       createUser
         should set the password if given:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  9) task: accounts
       createUser
         should complain if the password is too short:
     TypeError: Cannot read property should of undefined
      at odk/backend/test/integration/task/account.js:40:49
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.transaction (node_modules/slonik/dist/src/connectionMethods/transaction.js:22:24)
      at async Object.createConnection (node_modules/slonik/dist/src/factories/createConnection.js:99:22)

  10) task: accounts
       promoteUser
         should promote a user account to admin:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  11) task: accounts
       promoteUser
         should log an audit entry:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  12) task: accounts
       setUserPassword
         should set a user password:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  13) task: accounts
       setUserPassword
         should complain about a password that is too short:
     TypeError: Cannot read property should of undefined
      at odk/backend/test/integration/task/account.js:84:49
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.transaction (node_modules/slonik/dist/src/connectionMethods/transaction.js:22:24)
      at async Object.createConnection (node_modules/slonik/dist/src/factories/createConnection.js:99:22)

  14) task: accounts
       setUserPassword
         should log an audit entry:
     error: relation "actees" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  15) task: analytics
       should not compute analytics if explicitly disabled:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  16) task: analytics
       should not compute analytics if analytics sent recently:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  17) task: analytics
       should send analytics if enabled and time to send:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  18) task: analytics
       should resend analytics if last attempt failed:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  19) task: analytics
       should log event and full report if analytics sent successfully:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  20) task: analytics
       should log request errors:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  21) task: config
       getConfiguration
         should fetch configuration by key:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  22) task: config
       setConfiguration
         should save configuration by key:
     error: relation "config" does not exist
      at Parser.parseErrorMessage (node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  23) task: runner
       should print failure details to stderr and exit nonzero:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/task/task.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  24) worker
       worker
         should restart if the process itself fails:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (odk/backend/test/integration/worker/worker.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by alxndrsn** [comment]
Try: https://mochajs.org/#-timeout-ms-t-ms

Thanks @sadiqkhoja

**Comment by matthew-white** [comment]
> Try: https://mochajs.org/#-timeout-ms-t-ms

This might be a useful hint to add to the contribution guide!
