### ISSUE TITLE
run-docker-postgres user does not have sufficient permissions to restore from backup

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-backend#714]
```
Error: psql:/tmp/tmp-1468134-3eaf343DhYnK:2: ERROR:  permission denied for relation pg_database

    at /odk/backend/lib/task/db.js:53:40
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.withFile (/odk/backend/node_modules/tmp-promise/index.js:18:12)
    at async pgrestore (/odk/backend/lib/task/db.js:47:3)
    at async tmp.withDir.unsafeCleanup (/odk/backend/lib/bin/restore.js:28:5)
    at async Object.withDir (/odk/backend/node_modules/tmp-promise/index.js:37:12)
    at async /odk/backend/lib/bin/restore.js:26:3
```

**Comment by alxndrsn** [comment]
After getting past that, subsequently:
```
    'pg_restore: error: could not execute query: ERROR:  permission denied to create database\n' +
```

**Comment by alxndrsn** [comment]
Next:
```
    'pg_restore: error: could not execute query: ERROR:  schema "public" already exists\n' +
```

**Comment by matthew-white** [comment]
@alxndrsn, this issue is different from #1383, right? When I see "permission denied to create database", that sounds like #1383. But from other comments, it also sounds like there are additional things going on here.

**Comment by alxndrsn** [comment]
> [@alxndrsn](https://github.com/alxndrsn), this issue is different from [#1383](https://github.com/getodk/central-backend/issues/1383), right?

Yes.

**Comment by alxndrsn** [comment]
# To recreate

```sh
make run-docker-postgres
make dev &
echo topSecret123 | node lib/bin/cli.js user-create --email admin@example.test
node lib/bin/cli.js user-promote --email admin@example.test
curl -X POST \
     -H 'x-forwarded-proto: https' \
     -H "Authorization: Basic $(echo -n 'admin@example.test:topSecret123' | base64)" \
     http://localhost:8383/v1/backup > backup.zip
node lib/bin/restore.js ./backup.zip
```

# Logs

```
$ node lib/bin/restore.js ./backup.zip 
Error: Command failed: pg_restore --no-acl -e -j 4 -F d -C -c -h localhost -U jubilant -d template1 /tmp/tmp-399619-Mja2aDXzDNku
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3983; 1262 16385 DATABASE jubilant jubilant
pg_restore: error: could not execute query: ERROR:  permission denied to create database
Command was: CREATE DATABASE jubilant WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';
...
```
